#!/usr/bin/env node
// Scaffold a new agent.
//
//   node scripts/new-engine.mjs <slug> "<Display Name>" [--icon 🤖] [--tier PRO] [--category AGENTS]
//
// Writes the Supabase migration that registers the engine, then prints the
// two snippets to paste (definitions.ts and terraform.tfvars) and the rest of
// the checklist. It deliberately does NOT edit those two files itself —
// they carry per-engine comments and choices a generator would flatten, and a
// wrong automatic edit in the SSO wiring is worse than a paste.
//
// See docs/infra/adding-an-engine.md for the whole path.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';

const MIGRATIONS = 'supabase/migrations';
const ORG_ID = '00000000-0000-0000-0000-000000000001';

function fail(msg) {
  console.error(`\n  error: ${msg}\n`);
  process.exit(1);
}

const argv = process.argv.slice(2);
const flags = {};
const positional = [];
for (let i = 0; i < argv.length; i++) {
  if (argv[i].startsWith('--')) flags[argv[i].slice(2)] = argv[++i];
  else positional.push(argv[i]);
}

const [slug, displayName] = positional;
if (!slug || !displayName) {
  fail('usage: node scripts/new-engine.mjs <slug> "<Display Name>" [--icon 🤖] [--tier PRO] [--category AGENTS]');
}
if (!/^[a-z][a-z0-9]*$/.test(slug)) {
  // The slug becomes a subdomain, a Cloud Run service name, a GCP service
  // account id and an env-var prefix. Lowercase alphanumeric is the
  // intersection of what all four accept.
  fail(`slug must be lowercase alphanumeric, got "${slug}"`);
}
if (slug.length < 3 || slug.length > 26) {
  // GCP service account ids are 6-30 chars; the module appends "-<job>-sched".
  fail(`slug must be 3-26 characters, got ${slug.length}`);
}

const icon = flags.icon ?? '🤖';
const tier = (flags.tier ?? 'PRO').toUpperCase();
if (!['FREE', 'PRO', 'VIP'].includes(tier)) fail(`--tier must be FREE, PRO or VIP`);

// Categories the engines explorer filters on. Free text in the schema, but an
// unknown value just makes the engine unfilterable in the UI.
const CATEGORIES = ['AGENTS', 'CONTENT', 'RESEARCH', 'STREAMING', 'TRADING'];
const category = (flags.category ?? 'AGENTS').toUpperCase();
if (!CATEGORIES.includes(category)) fail(`--category must be one of ${CATEGORIES.join(', ')}`);

if (!existsSync(MIGRATIONS)) fail(`run this from the repo root (${MIGRATIONS} not found)`);

const existing = readdirSync(MIGRATIONS).filter((f) => f.endsWith('.sql'));

// Check migration CONTENTS, not filenames. The pre-rebrand migrations still
// carry their original names (they are Supabase's applied-migration ledger and
// must not be renamed), so `0030` registers slug 'chalybclip' from a file
// called 0018_nexoclip_url_rename.sql. A filename check misses that and
// happily generates a duplicate slug, which then fails at apply time against
// the unique (org_id, slug) constraint.
const claimed = new RegExp(`'${slug}'`);
const clash = existing.find((f) => claimed.test(readFileSync(join(MIGRATIONS, f), 'utf8')));
if (clash) {
  fail(`slug "${slug}" is already registered in ${clash}`);
}
const next = String(
  Math.max(...existing.map((f) => parseInt(f.slice(0, 4), 10)).filter(Number.isFinite)) + 1,
).padStart(4, '0');

const filename = `${next}_register_${slug}_engine.sql`;
const engineId = randomUUID();
const upper = slug.toUpperCase();

const sql = `-- =====================================================================
-- Chalyb — register ${displayName} as an engine.
--
-- Generated by scripts/new-engine.mjs. The rest of the checklist is in
-- docs/infra/adding-an-engine.md.
--
-- Ships as 'coming_soon' on purpose: the launch guard in
-- src/app/auth/launch/[slug]/route.ts refuses to send users to a non-active
-- engine, so nobody can reach a backend that is not serving yet. Flip to
-- 'active' once ${slug}.chalyb.com resolves and the secrets have values.
--
-- Idempotent: re-runnable.
-- =====================================================================

insert into public.engines
  (id, org_id, slug, name, icon, category, type, env, region, node,
   description, featured, status, tier_required)
values
  ('${engineId}',
   '${ORG_ID}',
   '${slug}', '${displayName.replace(/'/g, "''")}', '${icon}', '${category}', 'Agent',
   'PRODUCTION', 'us-central1', 'run-1',
   'TODO: describe ${displayName} — this text is what users read on the engine card.',
   false, 'coming_soon', '${tier}')
-- Conflict on the natural key (org_id, slug), not the generated id: that
-- makes the migration idempotent even if it is re-run after the row was
-- created some other way.
on conflict (org_id, slug) do update set
  name        = excluded.name,
  description = excluded.description,
  icon        = excluded.icon;

-- external_url / admin_api_base wire the SSO + provisioning contract.
-- Separate statement so re-running after a domain change updates in place.
update public.engines
set integration_mode      = 'external_sso_redirect',
    external_url          = 'https://${slug}.chalyb.com',
    admin_api_base        = 'https://${slug}.chalyb.com/api/admin',
    requires_provisioning = true
where slug = '${slug}';
`;

writeFileSync(join(MIGRATIONS, filename), sql);

console.log(`
  Created ${MIGRATIONS}/${filename}

  ── 1. Hub wiring — append to src/lib/engines/integrations/definitions.ts:

  createEngineIntegration({
    slug: '${slug}',
    displayName: '${displayName}',
  }),

  ── 2. Infrastructure — add to the engines map in infra/terraform/terraform.tfvars:

  ${slug} = {
    display_name = "${displayName}"
    # worker = { env = { ROLE = "worker" } }   # if it does background work
    # jobs   = { ... }                          # if it has CLI batch work
  }

  ── 3. The engine repo:

  Copy infra/engine-template/ into it and implement the three endpoints the
  factory calls (see src/lib/engines/integrations/factory.ts):

    POST {admin_api_base}/tenants
    POST {admin_api_base}/tenants/{tenant_id}/status
    GET  {external_url}/auth/sso?token=...

  ── 4. Secrets — after terraform apply, give each a value:

    ${slug}-admin-token     must equal ${upper}_ADMIN_TOKEN in Vercel
    ${slug}-sso-secret      must equal ${upper}_SSO_SECRET in Vercel
    ${slug}-database-url

  ── 5. Go live: point DNS at the Cloud Run URL, then flip the engine row to
     'active' and run reconcileEngineLinks('${slug}') from /dashboard/team.
`);
